//! Exporting the host database as an ssh_config `Include` fragment.
//!
//! `sshelf export` writes sshelf's **own** file (`ssh_config`, next to the config) and prints
//! the one `Include` line the user can add to `~/.ssh/config` themselves — sshelf never edits
//! that file, and never writes into `~/.ssh` at all. Once included, plain `ssh <name>` — and
//! everything that reads ssh config: `scp`/`sftp`, `rsync -e ssh`, git, editor remote
//! extensions — resolves sshelf hosts by name.
//!
//! Design points (docs/decisions.md D-023):
//! - **Derived data, deterministic.** Hosts render sorted by name with no timestamps, so the
//!   file changes only when the database does (dotfile/diff friendly). Once the file exists
//!   (creating it with `sshelf export` is the opt-in), every hosts save refreshes it.
//! - **Parity with `ssh::build_args`, minus sshelf-only plumbing.** No
//!   `StrictHostKeyChecking=accept-new` (that flag exists to keep the host-key prompt away
//!   from the askpass helper; plain interactive ssh should keep the user's own defaults) and
//!   no askpass wiring (an exported password-auth host simply prompts on the terminal).
//! - **Exact or visible.** `extra_args` are CLI flags, not config keywords: `-o Key=Value`
//!   pairs translate exactly; anything else is preserved as a comment, never guessed at.

use anyhow::{Context, Result};

use crate::model::{AuthMethod, Host, HostsFile};
use crate::paths::Paths;
use crate::store;

/// Render the full fragment: header + one block per host, site defaults resolved, sorted by
/// name (case-insensitive). `include_path` is only echoed in the header hint.
pub fn render(file: &HostsFile, include_path: &str) -> String {
    let mut hosts: Vec<Host> = file
        .hosts
        .iter()
        .map(|h| h.with_site_defaults(&file.sites))
        .collect();
    hosts.sort_by(|a, b| {
        a.name
            .to_lowercase()
            .cmp(&b.name.to_lowercase())
            .then_with(|| a.name.cmp(&b.name))
    });

    let mut out = format!(
        "# Generated by sshelf — do not edit (rewritten whenever hosts change).\n\
         # Manage hosts in sshelf; this file is derived from its database.\n\
         #\n\
         # To use it, add this line to your ~/.ssh/config (sshelf never edits that file):\n\
         #   Include {include_path}\n"
    );
    for h in &hosts {
        out.push('\n');
        out.push_str(&render_host(h));
    }
    out
}

/// One `Host` block (or a skip-comment when the name can't be a safe Host pattern).
fn render_host(h: &Host) -> String {
    let Some(pattern) = host_pattern(&h.name) else {
        // {:?} escapes the name, so a hostile name can't inject config lines via this comment.
        return format!(
            "# skipped {:?}: the name can't be an ssh_config Host pattern\n",
            h.name
        );
    };
    let mut b = format!("Host {pattern}\n");
    b.push_str(&format!("  HostName {}\n", arg(&h.hostname)));
    if let Some(user) = &h.user {
        b.push_str(&format!("  User {}\n", arg(user)));
    }
    // Mirror build_args: an explicit 22 is ssh's default — omit it.
    if let Some(port) = h.port
        && port != 22
    {
        b.push_str(&format!("  Port {port}\n"));
    }
    if h.auth == AuthMethod::Key {
        for key in &h.identity_files {
            // Keep `~` unexpanded — ssh expands IdentityFile itself, and the fragment stays
            // portable across machines (unlike the exec path, there's no no-shell caveat).
            b.push_str(&format!("  IdentityFile {}\n", arg(key)));
        }
    }
    if !h.jump_hosts.is_empty() {
        b.push_str(&format!("  ProxyJump {}\n", arg(&h.jump_hosts.join(","))));
    }
    if let Some(extra) = &h.extra_args {
        let (options, rest) = translate_extra_args(extra);
        for (k, v) in options {
            b.push_str(&format!("  {k} {v}\n"));
        }
        if !rest.is_empty() {
            let note = rest.join(" ").replace(|c: char| c.is_control(), " ");
            b.push_str(&format!(
                "  # not exported (ssh flags, not config): {note}\n"
            ));
        }
    }
    b
}

/// The `Host` pattern token for a name: quoted when it contains spaces, `None` when it can't
/// be represented safely — empty, control chars, a `"`/`#`, or pattern metacharacters
/// (`*` `?` `!` `,`) that would make the entry match *other* names.
fn host_pattern(name: &str) -> Option<String> {
    let unsafe_char = |c: char| c.is_control() || matches!(c, '"' | '#' | '*' | '?' | '!' | ',');
    if name.is_empty() || name.chars().any(unsafe_char) {
        return None;
    }
    Some(arg(name))
}

/// Quote a value when it contains whitespace; strip control characters (they could otherwise
/// break a directive onto a new, attacker-chosen line).
fn arg(v: &str) -> String {
    let v = v.replace(|c: char| c.is_control(), " ");
    if v.chars().any(char::is_whitespace) {
        format!("\"{v}\"")
    } else {
        v
    }
}

/// Split raw `extra_args` into exact `-o Key=Value` translations (also the combined
/// `-oKey=Value` and `-o "Key Value"` spellings) and untranslatable leftovers.
fn translate_extra_args(extra: &str) -> (Vec<(String, String)>, Vec<String>) {
    let Some(tokens) = shlex::split(extra) else {
        // Unparseable (e.g. unbalanced quotes) — keep it visible rather than guessing.
        return (Vec::new(), vec![extra.to_string()]);
    };
    let mut options = Vec::new();
    let mut rest = Vec::new();
    let mut iter = tokens.into_iter();
    while let Some(tok) = iter.next() {
        let kv = if tok == "-o" {
            match iter.next() {
                Some(v) => v,
                None => {
                    rest.push(tok);
                    continue;
                }
            }
        } else if let Some(v) = tok.strip_prefix("-o").filter(|v| !v.is_empty()) {
            v.to_string()
        } else {
            rest.push(tok);
            continue;
        };
        // ssh's -o argument is "Key=Value" or "Key Value"; the keyword never contains either
        // separator, so split at whichever comes first ("SetEnv FOO=1" keys as SetEnv).
        match kv.find(['=', ' ']).map(|i| (&kv[..i], &kv[i + 1..])) {
            // Keyword must stay a plain word and the value a single line, or the directive
            // could smuggle extra config lines into the fragment.
            Some((k, v))
                if !k.is_empty()
                    && !v.is_empty()
                    && k.chars().all(|c| c.is_ascii_alphanumeric())
                    && !v.chars().any(|c| c.is_control()) =>
            {
                options.push((k.to_string(), v.to_string()));
            }
            _ => rest.push(format!("-o {kv}")),
        }
    }
    (options, rest)
}

/// Names that `render` would skip (for the CLI summary).
pub fn unexportable_names(file: &HostsFile) -> Vec<String> {
    file.hosts
        .iter()
        .filter(|h| host_pattern(&h.name).is_none())
        .map(|h| h.name.clone())
        .collect()
}

/// Write the fragment to its fixed location (atomic, `0600` like the rest of our files).
pub fn write(paths: &Paths, file: &HostsFile) -> Result<()> {
    let path = paths.ssh_config_file();
    let text = render(file, &path.display().to_string());
    store::atomic_write(&path, text.as_bytes(), 0o600)
        .with_context(|| format!("writing {}", path.display()))
}

/// Refresh the exported fragment **iff it already exists** — creating it with `sshelf export`
/// is the opt-in. Returns `None` when export isn't enabled. Callers treat an `Err` as
/// advisory: the fragment is derived data and must never block a hosts save.
pub fn refresh_if_exported(paths: &Paths, file: &HostsFile) -> Option<Result<()>> {
    paths.ssh_config_file().exists().then(|| write(paths, file))
}

/// True when `config_text` (the user's ssh config, read-only) already has an `Include` line
/// naming any of `candidates` — used only to skip the "add this line" hint.
pub fn already_included(config_text: &str, candidates: &[String]) -> bool {
    config_text.lines().any(|line| {
        let line = line.trim();
        line.get(..7)
            .is_some_and(|kw| kw.eq_ignore_ascii_case("include"))
            && candidates.iter().any(|c| line.contains(c.as_str()))
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::Site;

    fn file_with(hosts: Vec<Host>, sites: Vec<Site>) -> HostsFile {
        HostsFile {
            format_version: crate::model::CURRENT_FORMAT_VERSION,
            sites,
            hosts,
        }
    }

    #[test]
    fn minimal_host_renders_name_and_hostname_only() {
        let out = render(&file_with(vec![Host::new("web", "10.0.0.1")], vec![]), "/p");
        assert!(out.contains("Host web\n  HostName 10.0.0.1\n"));
        assert!(!out.contains("User "));
        assert!(!out.contains("Port "));
        assert!(!out.contains("IdentityFile"));
    }

    #[test]
    fn full_host_renders_all_directives() {
        let mut h = Host::new("db", "10.0.0.2");
        h.user = Some("mike".into());
        h.port = Some(5432);
        h.auth = AuthMethod::Key;
        h.identity_files = vec!["~/.ssh/a".into(), "~/.ssh/b".into()];
        h.jump_hosts = vec!["j1".into(), "j2".into()];
        let out = render(&file_with(vec![h], vec![]), "/p");
        assert!(out.contains("Host db\n"));
        assert!(out.contains("  User mike\n"));
        assert!(out.contains("  Port 5432\n"));
        assert!(out.contains("  IdentityFile ~/.ssh/a\n  IdentityFile ~/.ssh/b\n"));
        assert!(out.contains("  ProxyJump j1,j2\n"));
    }

    #[test]
    fn default_port_22_is_omitted() {
        let mut h = Host::new("web", "h");
        h.port = Some(22);
        assert!(!render(&file_with(vec![h], vec![]), "/p").contains("Port"));
    }

    #[test]
    fn identity_files_only_render_for_key_auth() {
        // Mirrors build_args: -i is gated on auth = key.
        let mut h = Host::new("box", "h");
        h.auth = AuthMethod::Password;
        h.identity_files = vec!["~/.ssh/k".into()];
        assert!(!render(&file_with(vec![h], vec![]), "/p").contains("IdentityFile"));
    }

    #[test]
    fn site_defaults_are_resolved() {
        let mut site = Site::new("prod");
        site.user = Some("deploy".into());
        site.jump_hosts = vec!["bastion".into()];
        let mut h = Host::new("web", "10.0.0.1");
        h.site = Some("prod".into());
        let out = render(&file_with(vec![h], vec![site]), "/p");
        assert!(out.contains("  User deploy\n"));
        assert!(out.contains("  ProxyJump bastion\n"));
    }

    #[test]
    fn output_is_sorted_and_deterministic() {
        let f = file_with(
            vec![Host::new("zeta", "h1"), Host::new("Alpha", "h2")],
            vec![],
        );
        let out = render(&f, "/p");
        assert!(out.find("Host Alpha").unwrap() < out.find("Host zeta").unwrap());
        assert_eq!(out, render(&f, "/p"));
    }

    #[test]
    fn no_sshelf_only_plumbing_leaks_into_the_export() {
        let mut h = Host::new("web", "h");
        h.auth = AuthMethod::Password;
        let out = render(&file_with(vec![h], vec![]), "/p");
        assert!(!out.contains("StrictHostKeyChecking"));
        assert!(!out.contains("askpass"));
    }

    #[test]
    fn names_are_quoted_or_skipped() {
        assert_eq!(host_pattern("my host").as_deref(), Some("\"my host\""));
        for bad in ["", "we\"b", "a#b", "web*", "w?b", "!web", "a,b", "a\nb"] {
            assert!(host_pattern(bad).is_none(), "{bad:?} should be skipped");
        }
        let mut h = Host::new("web*", "h");
        h.user = Some("u".into());
        let out = render(&file_with(vec![h], vec![]), "/p");
        assert!(out.contains("# skipped \"web*\""));
        assert!(!out.contains("Host web*"));
        assert!(!out.contains("User u")); // nothing else from the skipped host leaks
    }

    #[test]
    fn extra_args_o_options_translate_exactly() {
        let (opts, rest) =
            translate_extra_args("-o ServerAliveInterval=30 -oCompression=yes -o \"SetEnv FOO=1\"");
        assert_eq!(
            opts,
            vec![
                ("ServerAliveInterval".to_string(), "30".to_string()),
                ("Compression".to_string(), "yes".to_string()),
                ("SetEnv".to_string(), "FOO=1".to_string()),
            ]
        );
        assert!(rest.is_empty());
    }

    #[test]
    fn extra_args_leftovers_become_a_comment_not_directives() {
        let mut h = Host::new("gui", "h");
        h.extra_args = Some("-X -o ServerAliveInterval=30".into());
        let out = render(&file_with(vec![h], vec![]), "/p");
        assert!(out.contains("  ServerAliveInterval 30\n"));
        assert!(out.contains("# not exported (ssh flags, not config): -X"));
        assert!(!out.contains("\n  -X"));
    }

    #[test]
    fn hostile_option_values_cannot_inject_directives() {
        let mut h = Host::new("evil", "h");
        h.extra_args = Some("-o \"ProxyCommand=x\ny Malicious yes\"".into());
        let out = render(&file_with(vec![h], vec![]), "/p");
        // The multi-line value lands in a single sanitized comment line, not as directives.
        assert!(!out.contains("\nMalicious"));
        assert!(!out.contains("\ny Malicious"));
    }

    #[test]
    fn unexportable_names_lists_only_the_bad_ones() {
        let f = file_with(vec![Host::new("ok", "h"), Host::new("bad*", "h")], vec![]);
        assert_eq!(unexportable_names(&f), vec!["bad*".to_string()]);
    }

    #[test]
    fn refresh_only_when_the_file_exists() {
        let dir = std::env::temp_dir().join(format!("sshelf-export-{}", ulid::Ulid::new()));
        std::fs::create_dir_all(&dir).unwrap();
        let paths = Paths {
            config_dir: dir.clone(),
            data_dir: dir.join("data"),
            config_file_override: None,
        };
        let f = file_with(vec![Host::new("web", "10.0.0.1")], vec![]);

        // Not exported yet → refresh is a no-op.
        assert!(refresh_if_exported(&paths, &f).is_none());
        assert!(!paths.ssh_config_file().exists());

        // Opt in by exporting once; from then on refresh rewrites it.
        write(&paths, &f).unwrap();
        let f2 = file_with(vec![Host::new("db", "10.0.0.9")], vec![]);
        refresh_if_exported(&paths, &f2).unwrap().unwrap();
        let text = std::fs::read_to_string(paths.ssh_config_file()).unwrap();
        assert!(text.contains("Host db") && !text.contains("Host web"));
    }

    #[test]
    fn already_included_matches_include_lines_only() {
        let candidates = vec!["/home/u/.config/sshelf/ssh_config".to_string()];
        assert!(already_included(
            "Host x\n  include /home/u/.config/sshelf/ssh_config\n",
            &candidates
        ));
        assert!(already_included(
            "Include ~/.config/sshelf/ssh_config",
            &["~/.config/sshelf/ssh_config".to_string()]
        ));
        // A comment or unrelated mention is not an Include.
        assert!(!already_included(
            "# /home/u/.config/sshelf/ssh_config\nHostName /home/u/.config/sshelf/ssh_config",
            &candidates
        ));
    }
}
